id: ACD9292D3
base_file: f62C1.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:53:24.246898
  last_modified_at: 2022-06-05 19:53:24.246903
