id: ACD9292D3
base_file: f51B6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:53:24.244392
  last_modified_at: 2022-06-05 19:53:24.244397
